NtAbcExam/NtAbcExam.Web/Areas/Admin/Models/AdminUserViewModel.cs
using System.Web.Mvc;

namespace NtAbcExam.Web.Areas.Admin.Models
{
    public class AdminUserViewModel
    {
        public int Id { get; set; }

        public string UserName { get; set; }

        public string UserPwd { get; set; }

        public int DeptId { get; set; }

        public string DeptName { get; set; }

        public bool IsSa { get; set; }

        public SelectList DeptSelectList { get; set; }
    }
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Controllers/AdminUserController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using NtAbcExam.Domain.DataModels;
using NtAbcExam.Domain.Models;
using NtAbcExam.Domain.Repositories;
using NtAbcExam.FrameWork.Data;
using NtAbcExam.FrameWork.Encryption;
using NtAbcExam.Web.Areas.Admin.Filters;
using NtAbcExam.Web.Areas.Admin.Models;
using NtAbcExam.Web.Models;

namespace NtAbcExam.Web.Areas.Admin.Controllers
{
    [AdminSeesion]
    public class AdminUserController : Controller
    {
        private readonly AdminUserRepository _adminUserRep = new AdminUserRepository();
        private readonly DepartmentRepository _deptRep = new DepartmentRepository();


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            var viewModel = new AdminUserViewModel();
            viewModel.DeptSelectList = new SelectList(_deptRep.GetAll(), "Id", "DeptName");
            return View(viewModel);
        }

        public ActionResult Edit(int id)
        {
            AdminUser adminUser = _adminUserRep.GetModelById(id);
            AdminUserViewModel viewModel = new AdminUserViewModel();
            Mapper.Map(adminUser, viewModel);
            viewModel.DeptSelectList = new SelectList(_deptRep.GetAll(), "Id", "DeptName");
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult GetList(ModelQuery modelQuery)
        {
            List<department> depts = _deptRep.GetAll();

            List<ModelFilter> filters = JsonConvert.DeserializeObject<List<ModelFilter>>(modelQuery.filters);
            modelQuery.filters = JsonConvert.SerializeObject(filters);

            int totalRow = 0;
            var adminUserList = _adminUserRep.Query(modelQuery, out totalRow);
            var adminUserViewModels = Mapper.Map<List<AdminUser>, List<AdminUserViewModel>>(adminUserList);

            //这儿应该用视图的，不应该用这个方法找的，但是数据少，。。。。
            foreach (var viewModel in adminUserViewModels)
            {
                var dept = depts.Find(f => f.Id == viewModel.DeptId);
                viewModel.DeptName = dept.DeptName;
            }

            GridModel grid = new GridModel();
            grid.total = totalRow;
            grid.rows = adminUserViewModels;
            return Content(JsonConvert.SerializeObject(grid));
        }

        [HttpPost]
        public ActionResult AddNew(AdminUserViewModel viewModel)
        {
            ResultModel result = new ResultModel();
            AdminUser adminUser = new AdminUser();
            Mapper.Map(viewModel, adminUser);
            result.IsSuccess = _adminUserRep.Add(adminUser) > 0;
            return Json(result);
        }

        [HttpPost]
        public ActionResult EditSave(AdminUserViewModel viewModel)
        {
            ResultModel result = new ResultModel();
            AdminUser adminUser = _adminUserRep.GetModelById(viewModel.Id);
            Mapper.Map(viewModel, adminUser);
            result.IsSuccess = _adminUserRep.Update(adminUser) > 0;
            return Json(result);
        }

        public ActionResult Del(int id)
        {
            ResultModel result = new ResultModel();
            result.IsSuccess = false;
            var adminUser = _adminUserRep.GetModelById(id);
            if (adminUser != null)
            {
                result.IsSuccess = _adminUserRep.Remove(adminUser) > 0;
            }

            return Json(result);
        }

        public ActionResult IsExistUserName(string userName)
        {
            return Json(!_adminUserRep.Any(q => q.UserName == userName));
        }

        public ActionResult ResetPwd(int id)
        {
            ResultModel result = new ResultModel();
            result.IsSuccess = _adminUserRep.ChangePwd(id, "111111");
            return Json(result);
        }
    }
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Views/AdminUser/Add.cshtml
@model NtAbcExam.Web.Areas.Admin.Models.AdminUserViewModel
@{
    ViewBag.Title = "新建用户";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-md-12">
            <div class="ibox float-e-margins">
                 <div class="ibox-title">
                    <h5>新建用户</h5>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal" id="postform" action="@Url.Action("AddNew","AdminUser")">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">登录名：</label>
                            <div class="col-sm-9">
                                <input name="UserName" id="UserName" class="form-control" type="text" maxlength="20">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">登录密码：</label>
                            <div class="col-sm-9">
                                <input name="UserPwd" id="UserPwd" class="form-control" type="password" maxlength="20">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">所属部门：</label>
                            <div class="col-sm-9">
                                @Html.DropDownList("DeptId", Model.DeptSelectList, new { @class = "form-control m-b" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">所属角色：</label>
                            <div class="col-sm-9">
                                <select id="IsSa" name="IsSa" class="form-control m-b">
                                    <option value="false">部门管理员</option>
                                    <option value="true">超级管理员</option>
                                </select>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">
                                <button class="btn btn-primary" type="button" onclick="save()">保存</button>
                                <a href="@Url.Action("Index","AdminUser")" class="btn btn-white">取消</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $("#postform").validate({
            rules: {
                "LoginName": {
                    required: true,
                    maxlength: 11,
                    remote: {
                        url: '@Url.Action("IsExistUserName", "AdminUser")',
                        type: "POST",
                        data: {
                            "loginName": function () { return $("#UserName").val(); },
                        },
                        dataType: "json"
                    }
                }
            },
            messages: {
                "LoginName":
                {
                    "remote": "登录名称已存在"
                }
            },
            onkeyup: false,
            focusCleanup: true,
            success: "valid"
        });

        function save() {
            if ($("#postform").valid()) {
                $.ajax({
                    url: $("#postform").attr("action"),
                    type: $("#postform").attr("method"),
                    data: $('#postform').serialize(),
                    success: function (result) {
                        if (result.IsSuccess == true) {
                            layer.alert('操作成功', { icon: 1 }, function () {
                                location.href = '@Url.Action("Index", "AdminUser")';
                            });
                        } else {
                            layer.alert('操作失败', { icon: 2 });
                        }
                    },
                    error: function (result) {
                        alert(result);
                    }
                });
            }
        }
    </script>
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Views/AdminUser/Edit.cshtml
@model NtAbcExam.Web.Areas.Admin.Models.AdminUserViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-md-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>编辑用户</h5>
                </div>
                <div class="ibox-content">
                    <form method="post" class="form-horizontal" id="postform" action="@Url.Action("EditSave","AdminUser")">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">登录名：</label>
                            <div class="col-sm-9">
                                <input name="UserName" id="UserName" readonly="readonly"
                                       value="@Model.UserName" class="form-control" type="text" maxlength="20">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">登录密码：</label>
                            <div class="col-sm-9">
                                <input name="UserPwd" id="UserPwd" class="form-control"
                                       type="password" maxlength="20">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">所属部门：</label>
                            <div class="col-sm-9">
                                @Html.DropDownList("DeptId", Model.DeptSelectList, new { @class = "form-control m-b" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">所属角色：</label>
                            <div class="col-sm-9">
                                <select id="IsSa" name="IsSa" class="form-control m-b">
                                    <option @(Model.IsSa ? "selected='selected'" : "") value="false">部门管理员</option>
                                    <option @(!Model.IsSa ? "selected='selected" : "") value="true">超级管理员</option>
                                </select>
                            </div>
                        </div>

                        <input type="hidden" id="Id" name="Id" value="@Model.Id" />
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">
                                <button class="btn btn-primary" type="button" onclick="save()">保存</button>
                                <a href="@Url.Action("Index","AdminUser")" class="btn btn-white">取消</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        function save() {
            $.ajax({
                url: $("#postform").attr("action"),
                type: $("#postform").attr("method"),
                data: $('#postform').serialize(),
                success: function (result) {
                    if (result.IsSuccess == true) {
                        layer.alert('操作成功', { icon: 1 }, function () {
                            location.href = '@Url.Action("Index", "AdminUser")';
                        });
                    } else {
                        layer.alert('操作失败', { icon: 2 });
                    }
                },
                error: function (result) {
                    alert(result);
                }
            });
        }
    </script>
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Views/AdminUser/Index.cshtml
@using NtAbcExam.Web.Common

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section Style{
    <link href=@Url.Content("~/Areas/Admin/style/css/plugins/bootstrap-table/bootstrap-table.min.css") rel="stylesheet" />
    <script src=@Url.Content("~/Areas/Admin/scripts/plugins/bootstrap-table/bootstrap-table.min.js")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/plugins/bootstrap-table/locale/bootstrap-table-zh-CN.min.js")></script>

}
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>用户</h5>
                </div>
                <div class="ibox-content">
                    <div class="row m-b-sm m-t-sm text-right" style="margin-left:5px; margin-right:3px;">
                        <form id="searchParams" class="form-inline">
                            <div style="float:left;">
                                <a href="@Url.Action("Add", "AdminUser")" class="btn btn-primary">新建</a>
                            </div>
                            <div class="form-group">
                                <input type="text" id="UserName" name="UserName" data-operate-type="Like" placeholder="请输入用户名" class="input-sm form-control">
                                <button type="button" class="btn btn-sm btn-primary" id="btnSearch"> 搜索</button>
                            </div>
                        </form>
                    </div>

                    <div class="data-list">
                        <table id="grid"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            //初始化Table
            var oTable = new TableInit();
            oTable.Init();

            //初始化Button的点击事件
            var oButtonInit = new ButtonInit();
            oButtonInit.Init();
        });


        var TableInit = function () {
            var oTableInit = new Object();
            //初始化Table
            oTableInit.Init = function () {
                $('#grid').bootstrapTable({
                    url: '@Url.Action("GetList","AdminUser")',         //请求后台的URL（*）
                    method: 'post',                      //请求方式（*）
                    toolbar: '#toolbar',                //工具按钮用哪个容器
                    striped: true,                      //是否显示行间隔色
                    cache: false,                       //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
                    pagination: true,                   //是否显示分页（*）
                    sortable: false,                     //是否启用排序
                    sortOrder: "asc",                   //排序方式
                    queryParams: oTableInit.queryParams,//传递参数（*）
                    sidePagination: "server",           //分页方式：client客户端分页，server服务端分页（*）
                    pageNumber: 1,                       //初始化加载第一页，默认第一页
                    pageSize: @GlobalVar.PageSize,      //每页的记录行数（*）
                    pageList: [10, 20, 50, 100],        //可供选择的每页的行数（*）
                    search: false,                       //是否显示表格搜索，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
                    strictSearch: true,
                    showColumns: false,                  //是否显示所有的列
                    showRefresh: false,                  //是否显示刷新按钮
                    minimumCountColumns: 2,             //最少允许的列数
                    clickToSelect: true,                //是否启用点击选中行
                    height: 550,                        //行高，如果没有设置height属性，表格自动根据记录条数觉得表格高度
                    uniqueId: "ID",                     //每一行的唯一标识，一般为主键列
                    showToggle: false,                  //是否显示详细视图和列表视图的切换按钮
                    cardView: false,                    //是否显示详细视图
                    detailView: false,                   //是否显示父子表
                    columns: [{
                        checkbox: true
                    },
                    {
                        field: 'UserName',
                        title: '用户名'
                    },
                    {
                        field: 'DeptName',
                        title: '部门'
                    },
                    {
                        field: 'IsSa',
                        title: '角色',
                        formatter:function(value, row, index) {
                            if (value) {
                                return "超级管理员";
                            }
                            else {
                                return "部门管理员";
                            }
                        }
                    },
                    {

                        field: 'operate',
                        title: '操作',
                        width: 200,
                        align: 'center',
                        valign: 'middle',
                        formatter: operateFormatter,
                        events: operateEvents
                    }]
                });
            };

            //得到查询的参数
            oTableInit.queryParams = function (params) {
                var temp = {
                    modelQuery: getQueryParams(params)
                };
                return temp;
            };
            return oTableInit;
        };

        var ButtonInit = function () {
            var oInit = new Object();
            var postdata = {};

            oInit.Init = function () {
                //初始化页面上面的按钮事件
            };

            return oInit;
        };

        function getQueryParams(params) {
            var query = {
                limit: params.limit,
                offset: params.offset,
                order: params.order,
                ordername: params.sort,
                filters: getSerachJson()
            };
            //alert(JSON.stringify(query));
            return query;
        }

        function getSerachJson() {
            var searchParames = $('#searchParams').serializeArray();      // jQuery推荐方式
            $.each(searchParames, function (index, data) {
                if (data != undefined) {
                    data.operType = $('[name="' + data.name + '"]', $('#searchParams')).data("operate-type");
                    if (data.operType == "Between") {
                        var inputId1 = $('[name="' + data.name + '"]', $('#searchParams')).data("bind-datemin");
                        var inputId2 = $('[name="' + data.name + '"]', $('#searchParams')).data("bind-datemax");
                        var minVal = $("#" + inputId1).val();
                        var maxVal = $("#" + inputId2).val();

                        if (minVal == undefined || minVal == "") {
                            minVal = "1900-01-01 00:00:00";
                        } else {
                            minVal += " 00:00:00";
                        }
                        if (maxVal == undefined || maxVal == "") {
                            maxVal = "2100-12-31 23:59:59";
                        } else {
                            maxVal += " 23:59:59";
                        }

                        data.value = minVal + "," + maxVal;
                    }
                }
            });
            var jsonFilters = JSON.stringify(searchParames);
            return jsonFilters;
        }

        function operateFormatter(value, row, index) {
            //alert(value);
            return [
                '<a id="update" href="@Url.Action("Edit","AdminUser")?id=' + row.Id + '" title="编辑">编辑</a>',
                 '&nbsp;&nbsp;',
                 '<a id="resetPwd" href="javascript:" title="重置密码">重置密码</a>',
                '&nbsp;&nbsp;',
                '<a id="remove" href="javascript:" title="删除">删除</a>'
            ].join('');
        }

        $("#btnSearch").click(function () {
            $("#grid").bootstrapTable('refresh');
        });

        window.operateEvents = {
            'click #resetPwd': function (e, value, row) {
                layer.confirm('是否确认要重置密码？', { icon: 3, title: '提示' }, function (index) {
                    $.ajax({
                        url: '@Url.Action("ResetPwd", "AdminUser")',
                        type: "post",
                        data: { "userId": row.Id },
                        success: function (result) {
                            if (result.IsSuccess == true) {
                                layer.alert('成功', { icon: 1 });
                                $("#grid").bootstrapTable('refresh');
                            }
                            else {
                                layer.alert('操作失败', { icon: 2 });
                                layer.closeAll();
                            }
                        },
                        error: function (result) {
                            alert(result);
                        }
                    });
                    layer.close(index);
                });
            },
            'click #remove': function (e, value, row) {
                layer.confirm('确定要删除这条记录吗？', { icon: 3, title: '提示' }, function (index) {
                    $.ajax({
                        url: '@Url.Action("Del", "AdminUser")',
                        type: "post",
                        data: { "id": row.Id },
                        success: function (result) {
                            if (result.IsSuccess == true) {
                                $("#grid").bootstrapTable('refresh');
                            }
                            else {
                                layer.alert('操作失败', { icon: 2 });
                                layer.closeAll();
                            }
                        },
                        error: function (result) {
                            alert(result);
                        }
                    });
                    layer.close(index);
                });
            }
        };
    </script>
}