NtAbcExam/NtAbcExam.Web/Areas/Admin/Models/LoginViewModel.cs
namespace NtAbcExam.Web.Areas.Admin.Models
{
    public class LoginViewModel
    {
        public string LoginName { get; set; }

        public string LoginPwd { get; set; }

        public string ValidateCode { get; set; }

    }
}

NtAbcExam/NtAbcExam.Web/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NtAbcExam.Web.Models
{
    public class LoginViewModel
    {
        [Display(Name = "账号")]
        [Required]
        [StringLength(20)]
        public string UserId { get; set; }

        [Display(Name = "密码")]
        [Required]
        [StringLength(32)]
        public string UserPwd { get; set; }
    }
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Controllers/DeptController.cs
using System.Collections.Generic;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using NtAbcExam.Domain.Models;
using NtAbcExam.Domain.Repositories;
using NtAbcExam.FrameWork.Data;
using NtAbcExam.Web.Areas.Admin.Filters;
using NtAbcExam.Web.Areas.Admin.Models;
using NtAbcExam.Web.Models;

namespace NtAbcExam.Web.Areas.Admin.Controllers
{
    [AdminSeesion]
    public class DeptController : Controller
    {
        private readonly DepartmentRepository _deptRep = new DepartmentRepository();
        // GET: Admin/Dept
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            department dept = _deptRep.GetModelById(id);
            DeptViewModel viewModel = new DeptViewModel();
            Mapper.Map(dept, viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult GetList(ModelQuery modelQuery)
        {
            List<ModelFilter> filters = JsonConvert.DeserializeObject<List<ModelFilter>>(modelQuery.filters);
            modelQuery.filters = JsonConvert.SerializeObject(filters);

            int totalRow = 0;
            var deptList = _deptRep.Query(modelQuery, out totalRow);
            var deptViewModels = Mapper.Map<List<department>, List<DeptViewModel>>(deptList);

            GridModel grid = new GridModel();
            grid.total = totalRow;
            grid.rows = deptViewModels;
            return Content(JsonConvert.SerializeObject(grid));
        }

        [HttpPost]
        public ActionResult AddNew(DeptViewModel deptViewModel)
        {
            ResultModel result = new ResultModel();
            department dept = new department();
            Mapper.Map(deptViewModel, dept);
            result.IsSuccess = _deptRep.Add(dept) > 0;
            return Json(result);
        }

        [HttpPost]
        public ActionResult EditSave(DeptViewModel deptViewModel)
        {
            ResultModel result = new ResultModel();
            department dept = _deptRep.GetModelById(deptViewModel.Id);
            Mapper.Map(deptViewModel, dept);
            result.IsSuccess = _deptRep.Update(dept) > 0;
            return Json(result);
        }

        public ActionResult Del(int id)
        {
            ResultModel result = new ResultModel();
            result.IsSuccess = false;
            var dept = _deptRep.GetModelById(id);
            if (dept != null)
            {
                result.IsSuccess = _deptRep.Remove(dept) > 0;
            }

            return Json(result);
        }

        public ActionResult IsExistDeptName(int id, string deptName)
        {
            return Json(!_deptRep.Any(q => q.Id != id && q.DeptName == deptName));
        }
    }
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Controllers/EmpController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using NtAbcExam.Domain.Models;
using NtAbcExam.Domain.Repositories;
using NtAbcExam.FrameWork.Data;
using NtAbcExam.FrameWork.Encryption;
using NtAbcExam.Web.Areas.Admin.Common;
using NtAbcExam.Web.Areas.Admin.Filters;
using NtAbcExam.Web.Areas.Admin.Models;
using NtAbcExam.Web.Models;

namespace NtAbcExam.Web.Areas.Admin.Controllers
{
    [AdminSeesion]
    public class EmpController : Controller
    {
        private readonly CadreInfoRepository _cadreInfoRep = new CadreInfoRepository();
        private readonly DepartmentRepository _deptRep = new DepartmentRepository();

        // GET: Admin/Emp
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            var viewModel = new EmpViewModel();
            viewModel.DeptSelectList = new SelectList(_deptRep.GetAll(), "Id", "DeptName");
            return View(viewModel);
        }

        public ActionResult Edit(string userId)
        {
            var emp = _cadreInfoRep.GetModelByUserId(userId);
            var viewModel = new EmpViewModel();
            Mapper.Map(emp, viewModel);
            viewModel.DeptSelectList = new SelectList(_deptRep.GetAll(), "Id", "DeptName");

            return View(viewModel);
        }

        public ActionResult Import(string aa)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Import(HttpPostedFileBase fileBase)
        {
            var file = Request.Files["files"];
            //int deptId = int.Parse(Request.Form["DeptId"]);

            if (file == null || file.ContentLength <= 0)
            {
                ViewBag.error = "文件不能为空";
                return View();
            }

            var filename = Path.GetFileName(file.FileName);
            var fileEx = Path.GetExtension(filename); //获取上传文件的扩展名
            var noFileName = Path.GetFileNameWithoutExtension(filename); //获取无扩展名的文件名
            const string fileType = ".xls,.xlsx"; //定义上传文件的类型字符串
            var newFileName = noFileName + DateTime.Now.ToString("yyyyMMddhhmmss") + fileEx;
            if (fileEx != null && !fileType.Contains(fileEx))
            {
                ViewBag.error = "文件类型不对，只能导入xls和xlsx格式的文件";
                return View();
            }
            string path = AppDomain.CurrentDomain.BaseDirectory + "uploads/excel/";
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            string savePath = Path.Combine(path, newFileName);
            file.SaveAs(savePath);

            var expImp = new ExportImport();
            var dt = expImp.GetFillData(savePath, false);
            if (dt == null)
            {
                ViewBag.Error = "导入的数据文件格式不正确";
                return View();
            }
            var importCount = dt.Rows.Count;
            if (importCount == 0)
            {
                ViewBag.Error = "导入的数据文件为空";
                return View();
            }

            string message;
            if (!CheckExcel(ref dt, out message))
            {
                ViewBag.Error = "导入失败";
                return View();
            }
            if (dt.Rows.Count == 0)
            {
                ViewBag.Error = "无正确的数据可导入";
                return View();
            }

            var empList = new List<cadre_info>();
            foreach (DataRow dr in dt.Rows)
            {
                cadre_info emp = new cadre_info
                {
                    UserID = dr[0].ToString(),
                    UserName = dr[1].ToString(),
                    Pwd = dr[2].ToString(),
                    DeptId = AdminLoginHelper.LoginInfo.DeptId
                };

                empList.Add(emp);
            }

            //写库
            bool ret = _cadreInfoRep.Add(empList) > 0;
            ViewBag.Error = ret ? "导入成功" : "导入失败";

            return View();
        }

        private bool CheckExcel(ref DataTable dt, out string log)
        {
            log = "";
            bool isSuccess = true;
            try
            {
                for (var i = dt.Rows.Count - 1; i > -1; i--)
                {
                    var dr = dt.Rows[i];

                    if (dr[0] == null || dr[0].ToString().Trim() == "")
                    {
                        //isSuccess = false;
                        log = "第 " + (i + 2) + " 行，，此行被忽略。\r\n" + log;
                        dt.Rows.Remove(dr);
                        continue;
                    }

                    if (dr[1] == null || dr[1].ToString().Trim() == "")
                    {
                        //isSuccess = false;
                        log = "第 " + (i + 2) + " 行，，此行被忽略。\r\n" + log;
                        dt.Rows.Remove(dr);
                        continue;
                    }
                }
            }
            catch (Exception ex)
            {
                log = "非系统导入模板==>" + ex.Message;
                return false;
            }
            return isSuccess;
        }

        [HttpPost]
        public ActionResult GetList(ModelQuery modelQuery)
        {
            List<department> depts = _deptRep.GetAll();

            List<ModelFilter> filters = JsonConvert.DeserializeObject<List<ModelFilter>>(modelQuery.filters);
            modelQuery.filters = JsonConvert.SerializeObject(filters);

            int totalRow = 0;
            var cadreInfos = _cadreInfoRep.Query(modelQuery, out totalRow);
            var empViewModels = Mapper.Map<List<cadre_info>, List<EmpViewModel>>(cadreInfos);

            //这儿应该用视图的，不应该用这个方法找的，但是数据少，。。。。
            foreach (var viewModel in empViewModels)
            {
                var dept = depts.Find(f => f.Id == viewModel.DeptId);
                viewModel.DeptName = dept.DeptName;
            }

            GridModel grid = new GridModel();
            grid.total = totalRow;
            grid.rows = empViewModels;
            return Content(JsonConvert.SerializeObject(grid));
        }

        [HttpPost]
        public ActionResult AddNew(EmpViewModel viewModel)
        {
            ResultModel result = new ResultModel();
            if (_cadreInfoRep.Any(q => q.UserID == viewModel.UserId))
            {
                result.IsSuccess = false;
                result.Msg = "身份证号码已存在";
                Json(result);
            }

            cadre_info adminUser = new cadre_info();
            Mapper.Map(viewModel, adminUser);
            result.IsSuccess = _cadreInfoRep.Add(adminUser) > 0;
            return Json(result);
        }

        [HttpPost]
        public ActionResult EditSave(EmpViewModel viewModel)
        {
            ResultModel result = new ResultModel();
            if (_cadreInfoRep.Any(q => q.Id != viewModel.Id && q.UserID == viewModel.UserId))
            {
                result.IsSuccess = false;
                result.Msg = "身份证号码已存在";
                Json(result);
            }
            cadre_info cadreInfo = _cadreInfoRep.GetModelByUserId(viewModel.UserId);
            Mapper.Map(viewModel, cadreInfo);
            result.IsSuccess = _cadreInfoRep.Update(cadreInfo) > 0;
            return Json(result);
        }

        public ActionResult Del(int id)
        {
            ResultModel result = new ResultModel();
            result.IsSuccess = false;
            var adminUser = _cadreInfoRep.GetModelById(id);
            if (adminUser != null)
            {
                result.IsSuccess = _cadreInfoRep.Remove(adminUser) > 0;
            }

            return Json(result);
        }

        public ActionResult IsExistUserId(int id, string userId)
        {
            return Json(!_cadreInfoRep.Any(q => q.Id != id && q.UserID == userId));
        }

        public ActionResult ResetPwd(string userId)
        {
            ResultModel result = new ResultModel();
            result.IsSuccess = _cadreInfoRep.ChangePwd(userId, Md5.Compute("111111"));
            return Json(result);
        }
    }
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Controllers/HomeController.cs
using System.Web.Mvc;
using NtAbcExam.Web.Areas.Admin.Common;
using NtAbcExam.Web.Areas.Admin.Filters;
using NtAbcExam.Web.Areas.Admin.Models;

namespace NtAbcExam.Web.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [AdminSeesion]
        // GET: Home
        public ActionResult Index()
        {
            return View(AdminLoginHelper.LoginInfo);
        }

        [AdminSeesion]
        public ActionResult Welcome()
        {
            return View();
        }


        public ActionResult Login()
        {

            return View();
        }

        public ActionResult Logout()
        {
            AdminLoginHelper.Logout();
            return RedirectToAction("Login", "Home");
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel viewModel)
        {
            if (string.IsNullOrWhiteSpace(viewModel.LoginName))
            {
                ModelState.AddModelError("", "用户名不能为空");
            }

            if (string.IsNullOrWhiteSpace(viewModel.LoginPwd))
            {
                ModelState.AddModelError("", "用户名不能为空");
            }


            if (AdminLoginHelper.Login(viewModel.LoginName, viewModel.LoginPwd))
            {
                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "用户名或密码错误");
            return View();
        }

    }
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Controllers/SubjectController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using Newtonsoft.Json;
using NtAbcExam.Domain.Models;
using NtAbcExam.Domain.Repositories;
using NtAbcExam.FrameWork.Data;
using NtAbcExam.Web.Areas.Admin.Filters;
using NtAbcExam.Web.Areas.Admin.Models;
using NtAbcExam.Web.Models;

namespace NtAbcExam.Web.Areas.Admin.Controllers
{
    [AdminSeesion]
    public class SubjectController : Controller
    {
        private readonly ExamSubjectRepository _subjectRep = new ExamSubjectRepository();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            exam_subject subject = _subjectRep.GetModelById(id);
            SubjectViewModel viewModel = new SubjectViewModel();
            Mapper.Map(subject, viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult GetList(ModelQuery modelQuery)
        {
            List<ModelFilter> filters = JsonConvert.DeserializeObject<List<ModelFilter>>(modelQuery.filters);
            modelQuery.filters = JsonConvert.SerializeObject(filters);

            int totalRow = 0;
            var subjectList = _subjectRep.Query(modelQuery, out totalRow);
            var subjectViewModels = Mapper.Map<List<exam_subject>, List<SubjectViewModel>>(subjectList);

            GridModel grid = new GridModel();
            grid.total = totalRow;
            grid.rows = subjectViewModels;
            return Content(JsonConvert.SerializeObject(grid));
        }

        [HttpPost]
        public ActionResult AddNew(SubjectViewModel viewModel)
        {
            ResultModel result = new ResultModel();
            exam_subject subject = new exam_subject();
            Mapper.Map(viewModel, subject);
            result.IsSuccess = _subjectRep.Add(subject) > 0;
            return Json(result);
        }

        [HttpPost]
        public ActionResult EditSave(SubjectViewModel viewModel)
        {
            ResultModel result = new ResultModel();
            exam_subject subject = _subjectRep.GetModelById(viewModel.Id);
            Mapper.Map(viewModel, subject);
            result.IsSuccess = _subjectRep.Update(subject) > 0;
            return Json(result);
        }

        public ActionResult Del(int id)
        {
            ResultModel result = new ResultModel();
            result.IsSuccess = false;
            var subject = _subjectRep.GetModelById(id);
            if (subject != null)
            {
                result.IsSuccess = _subjectRep.Remove(subject) > 0;
            }

            return Json(result);
        }

        public ActionResult IsExistSubjectName(int id, string subjectName)
        {
            return Json(!_subjectRep.Any(q => q.Id != id && q.SubjectName == subjectName));
        }
    }
}

NtAbcExam/NtAbcExam.Web/Areas/Admin/Views/Home/Import.cshtml
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-md-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>导入题库</h5>
                </div>
                <div class="ibox-content">
                    <form action="@Url.Action("Import", "Home")" id="form1" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">选择文件：</label>
                            <div class="col-sm-9">
                                <input type="file" name="files" data-filename-placement="inside" style="display: inline-block">
                                <p style="color: Red; text-align: center;">@ViewBag.error</p>
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">
                                <button class="btn btn-primary" type="submit" onclick="return save()">保存</button>
                                <a href="@Url.Action("Index","News")" class="btn btn-white">取消</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

NtAbcExam/NtAbcExam.Web/Areas/Admin/Views/Home/Index.cshtml
@using NtAbcExam.Web.Areas.Admin.Common
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <title>农行考试系统管理后台</title>
    <link href=@Url.Content("~/Areas/Admin/style/css/bootstrap.min.css") rel="stylesheet">
    <link href=@Url.Content("~/Areas/Admin/style/css/font-awesome.css") rel="stylesheet">
    <link href=@Url.Content("~/Areas/Admin/style/css/iconfont.css") rel="stylesheet">
    <link href=@Url.Content("~/Areas/Admin/style/css/animate.min.css") rel="stylesheet">
    <link href=@Url.Content("~/Areas/Admin/style/css/style.css") rel="stylesheet">
</head>
<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close">
                <i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <span><img alt="image" class="img-circle" src=@Url.Content("~/Areas/Admin/style/img/profle.png") /></span>
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs"><strong class="font-bold">@AdminLoginHelper.LoginInfo.UserName</strong></span>
                                </span>
                            </a>
                            <ul class="dropdown-menu animated fadeInRight m-t-xs">
                                <li>
                                    <a class="J_menuItem" href="mailbox.html">修改密码</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="@Url.Action("Logout","Home")">安全退出</a>
                                </li>
                            </ul>
                        </div>
                        <div class="logo-element">
                            H+
                        </div>
                    </li>


                    <li>
                        <a href="#">
                            <i class="iconfont">&#xe616;</i>
                            <span class="nav-label">考试题库</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="@Url.Action("ExamTestIndex", "Exam")" data-index="0">考试管理</a>
                                
                                <a class="J_menuItem" href="@Url.Action("Index", "Exam")" data-index="0">题库管理</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="#">
                            <i class="iconfont">&#xe616;</i>
                            <span class="nav-label">科目管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="@Url.Action("Index", "Subject")" data-index="0">科目管理</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="#">
                            <i class="iconfont">&#xe616;</i>
                            <span class="nav-label">部门管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="@Url.Action("Index","Dept")" data-index="0">部门管理</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="#">
                            <i class="iconfont">&#xe616;</i>
                            <span class="nav-label">操作员管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="@Url.Action("Index","AdminUser")" data-index="0">操作员管理</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="#">
                            <i class="iconfont">&#xe616;</i>
                            <span class="nav-label">人员管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="@Url.Action("Index","Emp")" data-index="0">人员管理</a>
                            </li>
                        </ul>
                    </li>



                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li class="hidden-xs">
                            <a class="navbar-minimalize btn " href="#"><i class="fa fa-bars"></i> </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="row content-tabs">
                <button class="roll-nav roll-left J_tabLeft">
                    <i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <a href="javascript:;" class="active J_menuTab" data-id="@Url.Action("Welcome","Home")">首页</a>
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight">
                    <i class="fa fa-forward"></i>
                </button>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">
                        关闭操作<span class="caret"></span>

                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive">
                            <a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <li class="J_tabCloseAll">
                            <a>关闭全部选项卡</a>
                        </li>
                        <li class="J_tabCloseOther">
                            <a>关闭其他选项卡</a>
                        </li>
                    </ul>
                </div>
                <a href="@Url.Action("Logout","Home")" class="roll-nav roll-right J_tabExit"><i class="fa fa fa-sign-out"></i> 退出</a>
            </div>
            <div class="row J_mainContent" id="content-main">
                <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="@Url.Action("Welcome","Home")" frameborder="0" data-id="@Url.Action("Welcome","Home")" seamless></iframe>
            </div>
        </div>
        <!--右侧部分结束-->
    </div>
    <script src=@Url.Content("~/Areas/Admin/scripts/jquery.min.js?v=2.1.4")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/plugins/layer/layer.js")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/bootstrap.min.js?v=3.3.6")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/plugins/metisMenu/jquery.metisMenu.js")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/plugins/slimscroll/jquery.slimscroll.min.js")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/hplus.min.js?v=4.1.0")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/contabs.min.js")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/plugins/pace/pace.min.js")></script>
</body>
</html>

NtAbcExam/NtAbcExam.Web/Areas/Admin/Views/Home/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>农行考试系统管理后台</title>

    <link href="@Url.Content("~/Areas/Admin/style/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Areas/Admin/style/css/font-awesome.css")" rel="stylesheet">

    <link href="@Url.Content("~/Areas/Admin/style/css/animate.min.css")" rel="stylesheet">
    <link href="@Url.Content("~/Areas/Admin/style/css/style.css")" rel="stylesheet">
</head>

<body class="gray-bg">
    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">ABC</h1>
            </div>
            <h3>农行考试系统管理后台</h3>
            @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { Areas = "Admin", @class = "m-t" }))
            {
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="用户名" required="" name="LoginName" id="LoginName">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="密码" required="" name="LoginPwd" id="LoginPwd">
                </div>
                <div style="text-align: left;color:#ff0000">
                    @Html.ValidationSummary(false)
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">登 录</button>

                <p class="text-muted text-center">
                    <a href="login.html#"><small>忘记密码了？</small></a>
                </p>
            }
        </div>
    </div>
    <script src=@Url.Content("~/Areas/Admin/scripts/jquery.min.js")></script>
    <script src=@Url.Content("~/Areas/Admin/scripts/bootstrap.min.js")></script>
</body>
</html>

NtAbcExam/NtAbcExam.Web/Areas/Admin/Views/Home/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox">
                <div class="ibox-content text-center">
                    <h3 class="m-b-xxs">写点什么</h3>
                </div>
            </div>
        </div>
    </div>
</div>